jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{env_var('SNOWFLAKE_ACCOUNT','')}}"
      user: "{{env_var('SNOWFLAKE_USER','')}}"
      private_key_path: "{{env_var('PRIVATE_KEY_PATH','')}}"
      private_key_passphrase: "{{env_var('PRIVATE_KEY_PASSPHRASE','')}}"
      role: "{{env_var('SNOWFLAKE_ROLE','')}}"
      database: "{{env_var('SNOWFLAKE_DATABASE','')}}"
      warehouse: "{{env_var('SNOWFLAKE_WAREHOUSE','')}}"
      schema: "{{env_var('SNOWFLAKE_SCHEMA','')}}"
      threads: "{{ env_var('DBT_THREADS',16) | int }}"
      client_session_keep_alive: "{{env_var('DBT_CLIENT_SESSION_KEEP_ALIVE', 'False') | as_bool }}"